[profile.default]
optimizer_runs = 44_444_444
via_ir = true
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out" },
]
solc = "0.8.28"
evm_version = "paris"
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
